// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _lec8Ex1_HH_
#define _lec8Ex1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Loop_for_Loop_proc.h"

namespace ap_rtl {

struct lec8Ex1 : public sc_module {
    // Port declarations 29
    sc_out< sc_lv<6> > in_r_address0;
    sc_out< sc_logic > in_r_ce0;
    sc_out< sc_lv<32> > in_r_d0;
    sc_in< sc_lv<32> > in_r_q0;
    sc_out< sc_logic > in_r_we0;
    sc_out< sc_lv<6> > in_r_address1;
    sc_out< sc_logic > in_r_ce1;
    sc_out< sc_lv<32> > in_r_d1;
    sc_in< sc_lv<32> > in_r_q1;
    sc_out< sc_logic > in_r_we1;
    sc_in< sc_lv<16> > a;
    sc_in< sc_lv<16> > b;
    sc_in< sc_lv<32> > c;
    sc_out< sc_lv<6> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_lv<32> > out_r_d0;
    sc_in< sc_lv<32> > out_r_q0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<6> > out_r_address1;
    sc_out< sc_logic > out_r_ce1;
    sc_out< sc_lv<32> > out_r_d1;
    sc_in< sc_lv<32> > out_r_q1;
    sc_out< sc_logic > out_r_we1;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;


    // Module declarations
    lec8Ex1(sc_module_name name);
    SC_HAS_PROCESS(lec8Ex1);

    ~lec8Ex1();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Loop_for_Loop_proc* Loop_for_Loop_proc_U0;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_ap_ready;
    sc_signal< sc_lv<6> > Loop_for_Loop_proc_U0_in_r_address0;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_in_r_ce0;
    sc_signal< sc_lv<6> > Loop_for_Loop_proc_U0_out_r_address0;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_out_r_ce0;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_out_r_we0;
    sc_signal< sc_lv<32> > Loop_for_Loop_proc_U0_out_r_d0;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_start_full_n;
    sc_signal< sc_logic > Loop_for_Loop_proc_U0_start_write;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_Loop_for_Loop_proc_U0_ap_continue();
    void thread_Loop_for_Loop_proc_U0_ap_start();
    void thread_Loop_for_Loop_proc_U0_start_full_n();
    void thread_Loop_for_Loop_proc_U0_start_write();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_in_r_address0();
    void thread_in_r_address1();
    void thread_in_r_ce0();
    void thread_in_r_ce1();
    void thread_in_r_d0();
    void thread_in_r_d1();
    void thread_in_r_we0();
    void thread_in_r_we1();
    void thread_out_r_address0();
    void thread_out_r_address1();
    void thread_out_r_ce0();
    void thread_out_r_ce1();
    void thread_out_r_d0();
    void thread_out_r_d1();
    void thread_out_r_we0();
    void thread_out_r_we1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
