// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "lec8Ex1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic lec8Ex1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic lec8Ex1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> lec8Ex1::ap_ST_fsm_state1 = "1";
const sc_lv<3> lec8Ex1::ap_ST_fsm_state2 = "10";
const sc_lv<3> lec8Ex1::ap_ST_fsm_state3 = "100";
const sc_lv<32> lec8Ex1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> lec8Ex1::ap_const_lv32_1 = "1";
const sc_lv<1> lec8Ex1::ap_const_lv1_0 = "0";
const sc_lv<6> lec8Ex1::ap_const_lv6_0 = "000000";
const sc_lv<32> lec8Ex1::ap_const_lv32_2 = "10";
const sc_lv<6> lec8Ex1::ap_const_lv6_3A = "111010";
const sc_lv<6> lec8Ex1::ap_const_lv6_39 = "111001";
const sc_lv<6> lec8Ex1::ap_const_lv6_38 = "111000";
const sc_lv<6> lec8Ex1::ap_const_lv6_37 = "110111";
const sc_lv<6> lec8Ex1::ap_const_lv6_36 = "110110";
const sc_lv<6> lec8Ex1::ap_const_lv6_35 = "110101";
const sc_lv<6> lec8Ex1::ap_const_lv6_34 = "110100";
const sc_lv<6> lec8Ex1::ap_const_lv6_33 = "110011";
const sc_lv<6> lec8Ex1::ap_const_lv6_32 = "110010";
const sc_lv<6> lec8Ex1::ap_const_lv6_31 = "110001";
const sc_lv<6> lec8Ex1::ap_const_lv6_30 = "110000";
const sc_lv<6> lec8Ex1::ap_const_lv6_2F = "101111";
const sc_lv<6> lec8Ex1::ap_const_lv6_2E = "101110";
const sc_lv<6> lec8Ex1::ap_const_lv6_2D = "101101";
const sc_lv<6> lec8Ex1::ap_const_lv6_2C = "101100";
const sc_lv<6> lec8Ex1::ap_const_lv6_2B = "101011";
const sc_lv<6> lec8Ex1::ap_const_lv6_2A = "101010";
const sc_lv<6> lec8Ex1::ap_const_lv6_29 = "101001";
const sc_lv<6> lec8Ex1::ap_const_lv6_28 = "101000";
const sc_lv<6> lec8Ex1::ap_const_lv6_27 = "100111";
const sc_lv<6> lec8Ex1::ap_const_lv6_26 = "100110";
const sc_lv<6> lec8Ex1::ap_const_lv6_25 = "100101";
const sc_lv<6> lec8Ex1::ap_const_lv6_24 = "100100";
const sc_lv<6> lec8Ex1::ap_const_lv6_23 = "100011";
const sc_lv<6> lec8Ex1::ap_const_lv6_22 = "100010";
const sc_lv<6> lec8Ex1::ap_const_lv6_21 = "100001";
const sc_lv<6> lec8Ex1::ap_const_lv6_20 = "100000";
const sc_lv<6> lec8Ex1::ap_const_lv6_1F = "11111";
const sc_lv<6> lec8Ex1::ap_const_lv6_1E = "11110";
const sc_lv<6> lec8Ex1::ap_const_lv6_1D = "11101";
const sc_lv<6> lec8Ex1::ap_const_lv6_1C = "11100";
const sc_lv<6> lec8Ex1::ap_const_lv6_1B = "11011";
const sc_lv<6> lec8Ex1::ap_const_lv6_1A = "11010";
const sc_lv<6> lec8Ex1::ap_const_lv6_19 = "11001";
const sc_lv<6> lec8Ex1::ap_const_lv6_18 = "11000";
const sc_lv<6> lec8Ex1::ap_const_lv6_17 = "10111";
const sc_lv<6> lec8Ex1::ap_const_lv6_16 = "10110";
const sc_lv<6> lec8Ex1::ap_const_lv6_15 = "10101";
const sc_lv<6> lec8Ex1::ap_const_lv6_14 = "10100";
const sc_lv<6> lec8Ex1::ap_const_lv6_13 = "10011";
const sc_lv<6> lec8Ex1::ap_const_lv6_12 = "10010";
const sc_lv<6> lec8Ex1::ap_const_lv6_11 = "10001";
const sc_lv<6> lec8Ex1::ap_const_lv6_10 = "10000";
const sc_lv<6> lec8Ex1::ap_const_lv6_F = "1111";
const sc_lv<6> lec8Ex1::ap_const_lv6_E = "1110";
const sc_lv<6> lec8Ex1::ap_const_lv6_D = "1101";
const sc_lv<6> lec8Ex1::ap_const_lv6_C = "1100";
const sc_lv<6> lec8Ex1::ap_const_lv6_B = "1011";
const sc_lv<6> lec8Ex1::ap_const_lv6_A = "1010";
const sc_lv<6> lec8Ex1::ap_const_lv6_9 = "1001";
const sc_lv<6> lec8Ex1::ap_const_lv6_8 = "1000";
const sc_lv<6> lec8Ex1::ap_const_lv6_7 = "111";
const sc_lv<6> lec8Ex1::ap_const_lv6_6 = "110";
const sc_lv<6> lec8Ex1::ap_const_lv6_5 = "101";
const sc_lv<6> lec8Ex1::ap_const_lv6_4 = "100";
const sc_lv<6> lec8Ex1::ap_const_lv6_3 = "11";
const sc_lv<6> lec8Ex1::ap_const_lv6_2 = "10";
const sc_lv<6> lec8Ex1::ap_const_lv6_1 = "1";
const sc_lv<6> lec8Ex1::ap_const_lv6_3F = "111111";
const sc_lv<6> lec8Ex1::ap_const_lv6_3E = "111110";
const sc_lv<6> lec8Ex1::ap_const_lv6_3D = "111101";
const sc_lv<6> lec8Ex1::ap_const_lv6_3C = "111100";
const sc_lv<6> lec8Ex1::ap_const_lv6_3B = "111011";
const sc_lv<17> lec8Ex1::ap_const_lv17_27 = "100111";
const sc_lv<1> lec8Ex1::ap_const_lv1_1 = "1";
const bool lec8Ex1::ap_const_boolean_1 = true;

lec8Ex1::lec8Ex1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lec8Ex1_mux_606_3bkb_U1 = new lec8Ex1_mux_606_3bkb<1,1,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,6,32>("lec8Ex1_mux_606_3bkb_U1");
    lec8Ex1_mux_606_3bkb_U1->din0(in_0);
    lec8Ex1_mux_606_3bkb_U1->din1(in_1);
    lec8Ex1_mux_606_3bkb_U1->din2(in_2);
    lec8Ex1_mux_606_3bkb_U1->din3(in_3);
    lec8Ex1_mux_606_3bkb_U1->din4(in_4);
    lec8Ex1_mux_606_3bkb_U1->din5(in_5);
    lec8Ex1_mux_606_3bkb_U1->din6(in_6);
    lec8Ex1_mux_606_3bkb_U1->din7(in_7);
    lec8Ex1_mux_606_3bkb_U1->din8(in_8);
    lec8Ex1_mux_606_3bkb_U1->din9(in_9);
    lec8Ex1_mux_606_3bkb_U1->din10(in_10);
    lec8Ex1_mux_606_3bkb_U1->din11(in_11);
    lec8Ex1_mux_606_3bkb_U1->din12(in_12);
    lec8Ex1_mux_606_3bkb_U1->din13(in_13);
    lec8Ex1_mux_606_3bkb_U1->din14(in_14);
    lec8Ex1_mux_606_3bkb_U1->din15(in_15);
    lec8Ex1_mux_606_3bkb_U1->din16(in_16);
    lec8Ex1_mux_606_3bkb_U1->din17(in_17);
    lec8Ex1_mux_606_3bkb_U1->din18(in_18);
    lec8Ex1_mux_606_3bkb_U1->din19(in_19);
    lec8Ex1_mux_606_3bkb_U1->din20(in_20);
    lec8Ex1_mux_606_3bkb_U1->din21(in_21);
    lec8Ex1_mux_606_3bkb_U1->din22(in_22);
    lec8Ex1_mux_606_3bkb_U1->din23(in_23);
    lec8Ex1_mux_606_3bkb_U1->din24(in_24);
    lec8Ex1_mux_606_3bkb_U1->din25(in_25);
    lec8Ex1_mux_606_3bkb_U1->din26(in_26);
    lec8Ex1_mux_606_3bkb_U1->din27(in_27);
    lec8Ex1_mux_606_3bkb_U1->din28(in_28);
    lec8Ex1_mux_606_3bkb_U1->din29(in_29);
    lec8Ex1_mux_606_3bkb_U1->din30(in_30);
    lec8Ex1_mux_606_3bkb_U1->din31(in_31);
    lec8Ex1_mux_606_3bkb_U1->din32(in_32);
    lec8Ex1_mux_606_3bkb_U1->din33(in_33);
    lec8Ex1_mux_606_3bkb_U1->din34(in_34);
    lec8Ex1_mux_606_3bkb_U1->din35(in_35);
    lec8Ex1_mux_606_3bkb_U1->din36(in_36);
    lec8Ex1_mux_606_3bkb_U1->din37(in_37);
    lec8Ex1_mux_606_3bkb_U1->din38(in_38);
    lec8Ex1_mux_606_3bkb_U1->din39(in_39);
    lec8Ex1_mux_606_3bkb_U1->din40(in_40);
    lec8Ex1_mux_606_3bkb_U1->din41(in_41);
    lec8Ex1_mux_606_3bkb_U1->din42(in_42);
    lec8Ex1_mux_606_3bkb_U1->din43(in_43);
    lec8Ex1_mux_606_3bkb_U1->din44(in_44);
    lec8Ex1_mux_606_3bkb_U1->din45(in_45);
    lec8Ex1_mux_606_3bkb_U1->din46(in_46);
    lec8Ex1_mux_606_3bkb_U1->din47(in_47);
    lec8Ex1_mux_606_3bkb_U1->din48(in_48);
    lec8Ex1_mux_606_3bkb_U1->din49(in_49);
    lec8Ex1_mux_606_3bkb_U1->din50(in_50);
    lec8Ex1_mux_606_3bkb_U1->din51(in_51);
    lec8Ex1_mux_606_3bkb_U1->din52(in_52);
    lec8Ex1_mux_606_3bkb_U1->din53(in_53);
    lec8Ex1_mux_606_3bkb_U1->din54(in_54);
    lec8Ex1_mux_606_3bkb_U1->din55(in_55);
    lec8Ex1_mux_606_3bkb_U1->din56(in_56);
    lec8Ex1_mux_606_3bkb_U1->din57(in_57);
    lec8Ex1_mux_606_3bkb_U1->din58(in_58);
    lec8Ex1_mux_606_3bkb_U1->din59(in_59);
    lec8Ex1_mux_606_3bkb_U1->din60(i_0_reg_1190);
    lec8Ex1_mux_606_3bkb_U1->dout(x_fu_1238_p62);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln24_1_fu_1216_p2);
    sensitive << ( sext_ln34_fu_1206_p1 );

    SC_METHOD(thread_add_ln24_fu_1369_p2);
    sensitive << ( res_reg_1443 );
    sensitive << ( mul_ln24_reg_1461 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln17_fu_1226_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln17_fu_1226_p2 );

    SC_METHOD(thread_i_fu_1232_p2);
    sensitive << ( i_0_reg_1190 );

    SC_METHOD(thread_icmp_ln17_fu_1226_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_1190 );

    SC_METHOD(thread_mul_ln24_fu_1364_p1);
    sensitive << ( sext_ln24_reg_1438 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mul_ln24_fu_1364_p2);
    sensitive << ( x_fu_1238_p62 );
    sensitive << ( mul_ln24_fu_1364_p1 );

    SC_METHOD(thread_out_0);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_0_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_1);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_10);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_10_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_11);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_11_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_12);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_12_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_13);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_13_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_14);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_14_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_15);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_15_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_16);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_16_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_17);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_17_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_18);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_18_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_19);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_19_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_1_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_2);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_20);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_20_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_21);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_21_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_22);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_22_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_23);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_23_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_24);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_24_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_25);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_25_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_26);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_26_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_27);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_27_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_28);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_28_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_29);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_29_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_2_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_3);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_30);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_30_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_31);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_31_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_32);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_32_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_33);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_33_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_34);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_34_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_35);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_35_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_36);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_36_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_37);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_37_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_38);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_38_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_39);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_39_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_3_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_4);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_40);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_40_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_41);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_41_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_42);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_42_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_43);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_43_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_44);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_44_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_45);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_45_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_46);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_46_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_47);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_47_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_48);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_48_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_49);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_49_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_4_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_5);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_50);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_50_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_51);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_51_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_52);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_52_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_53);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_53_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_54);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_54_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_55);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_55_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_56);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_56_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_57);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_57_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_58);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_58_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_59);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_59_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_5_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_6);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_6_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_7);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_7_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_8);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_8_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_9);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_fu_1373_p2 );

    SC_METHOD(thread_out_9_ap_vld);
    sensitive << ( i_0_reg_1190 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_res_fu_1210_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( c );

    SC_METHOD(thread_res_fu_1210_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( c );

    SC_METHOD(thread_res_fu_1210_p2);
    sensitive << ( res_fu_1210_p0 );
    sensitive << ( res_fu_1210_p1 );

    SC_METHOD(thread_sext_ln24_1_fu_1222_p1);
    sensitive << ( add_ln24_1_fu_1216_p2 );

    SC_METHOD(thread_sext_ln24_fu_1202_p1);
    sensitive << ( a );

    SC_METHOD(thread_sext_ln34_fu_1206_p1);
    sensitive << ( b );

    SC_METHOD(thread_y_fu_1373_p2);
    sensitive << ( sext_ln24_1_reg_1448 );
    sensitive << ( add_ln24_fu_1369_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln17_fu_1226_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "lec8Ex1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_0, "(port)in_0");
    sc_trace(mVcdFile, in_1, "(port)in_1");
    sc_trace(mVcdFile, in_2, "(port)in_2");
    sc_trace(mVcdFile, in_3, "(port)in_3");
    sc_trace(mVcdFile, in_4, "(port)in_4");
    sc_trace(mVcdFile, in_5, "(port)in_5");
    sc_trace(mVcdFile, in_6, "(port)in_6");
    sc_trace(mVcdFile, in_7, "(port)in_7");
    sc_trace(mVcdFile, in_8, "(port)in_8");
    sc_trace(mVcdFile, in_9, "(port)in_9");
    sc_trace(mVcdFile, in_10, "(port)in_10");
    sc_trace(mVcdFile, in_11, "(port)in_11");
    sc_trace(mVcdFile, in_12, "(port)in_12");
    sc_trace(mVcdFile, in_13, "(port)in_13");
    sc_trace(mVcdFile, in_14, "(port)in_14");
    sc_trace(mVcdFile, in_15, "(port)in_15");
    sc_trace(mVcdFile, in_16, "(port)in_16");
    sc_trace(mVcdFile, in_17, "(port)in_17");
    sc_trace(mVcdFile, in_18, "(port)in_18");
    sc_trace(mVcdFile, in_19, "(port)in_19");
    sc_trace(mVcdFile, in_20, "(port)in_20");
    sc_trace(mVcdFile, in_21, "(port)in_21");
    sc_trace(mVcdFile, in_22, "(port)in_22");
    sc_trace(mVcdFile, in_23, "(port)in_23");
    sc_trace(mVcdFile, in_24, "(port)in_24");
    sc_trace(mVcdFile, in_25, "(port)in_25");
    sc_trace(mVcdFile, in_26, "(port)in_26");
    sc_trace(mVcdFile, in_27, "(port)in_27");
    sc_trace(mVcdFile, in_28, "(port)in_28");
    sc_trace(mVcdFile, in_29, "(port)in_29");
    sc_trace(mVcdFile, in_30, "(port)in_30");
    sc_trace(mVcdFile, in_31, "(port)in_31");
    sc_trace(mVcdFile, in_32, "(port)in_32");
    sc_trace(mVcdFile, in_33, "(port)in_33");
    sc_trace(mVcdFile, in_34, "(port)in_34");
    sc_trace(mVcdFile, in_35, "(port)in_35");
    sc_trace(mVcdFile, in_36, "(port)in_36");
    sc_trace(mVcdFile, in_37, "(port)in_37");
    sc_trace(mVcdFile, in_38, "(port)in_38");
    sc_trace(mVcdFile, in_39, "(port)in_39");
    sc_trace(mVcdFile, in_40, "(port)in_40");
    sc_trace(mVcdFile, in_41, "(port)in_41");
    sc_trace(mVcdFile, in_42, "(port)in_42");
    sc_trace(mVcdFile, in_43, "(port)in_43");
    sc_trace(mVcdFile, in_44, "(port)in_44");
    sc_trace(mVcdFile, in_45, "(port)in_45");
    sc_trace(mVcdFile, in_46, "(port)in_46");
    sc_trace(mVcdFile, in_47, "(port)in_47");
    sc_trace(mVcdFile, in_48, "(port)in_48");
    sc_trace(mVcdFile, in_49, "(port)in_49");
    sc_trace(mVcdFile, in_50, "(port)in_50");
    sc_trace(mVcdFile, in_51, "(port)in_51");
    sc_trace(mVcdFile, in_52, "(port)in_52");
    sc_trace(mVcdFile, in_53, "(port)in_53");
    sc_trace(mVcdFile, in_54, "(port)in_54");
    sc_trace(mVcdFile, in_55, "(port)in_55");
    sc_trace(mVcdFile, in_56, "(port)in_56");
    sc_trace(mVcdFile, in_57, "(port)in_57");
    sc_trace(mVcdFile, in_58, "(port)in_58");
    sc_trace(mVcdFile, in_59, "(port)in_59");
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, c, "(port)c");
    sc_trace(mVcdFile, out_0, "(port)out_0");
    sc_trace(mVcdFile, out_0_ap_vld, "(port)out_0_ap_vld");
    sc_trace(mVcdFile, out_1, "(port)out_1");
    sc_trace(mVcdFile, out_1_ap_vld, "(port)out_1_ap_vld");
    sc_trace(mVcdFile, out_2, "(port)out_2");
    sc_trace(mVcdFile, out_2_ap_vld, "(port)out_2_ap_vld");
    sc_trace(mVcdFile, out_3, "(port)out_3");
    sc_trace(mVcdFile, out_3_ap_vld, "(port)out_3_ap_vld");
    sc_trace(mVcdFile, out_4, "(port)out_4");
    sc_trace(mVcdFile, out_4_ap_vld, "(port)out_4_ap_vld");
    sc_trace(mVcdFile, out_5, "(port)out_5");
    sc_trace(mVcdFile, out_5_ap_vld, "(port)out_5_ap_vld");
    sc_trace(mVcdFile, out_6, "(port)out_6");
    sc_trace(mVcdFile, out_6_ap_vld, "(port)out_6_ap_vld");
    sc_trace(mVcdFile, out_7, "(port)out_7");
    sc_trace(mVcdFile, out_7_ap_vld, "(port)out_7_ap_vld");
    sc_trace(mVcdFile, out_8, "(port)out_8");
    sc_trace(mVcdFile, out_8_ap_vld, "(port)out_8_ap_vld");
    sc_trace(mVcdFile, out_9, "(port)out_9");
    sc_trace(mVcdFile, out_9_ap_vld, "(port)out_9_ap_vld");
    sc_trace(mVcdFile, out_10, "(port)out_10");
    sc_trace(mVcdFile, out_10_ap_vld, "(port)out_10_ap_vld");
    sc_trace(mVcdFile, out_11, "(port)out_11");
    sc_trace(mVcdFile, out_11_ap_vld, "(port)out_11_ap_vld");
    sc_trace(mVcdFile, out_12, "(port)out_12");
    sc_trace(mVcdFile, out_12_ap_vld, "(port)out_12_ap_vld");
    sc_trace(mVcdFile, out_13, "(port)out_13");
    sc_trace(mVcdFile, out_13_ap_vld, "(port)out_13_ap_vld");
    sc_trace(mVcdFile, out_14, "(port)out_14");
    sc_trace(mVcdFile, out_14_ap_vld, "(port)out_14_ap_vld");
    sc_trace(mVcdFile, out_15, "(port)out_15");
    sc_trace(mVcdFile, out_15_ap_vld, "(port)out_15_ap_vld");
    sc_trace(mVcdFile, out_16, "(port)out_16");
    sc_trace(mVcdFile, out_16_ap_vld, "(port)out_16_ap_vld");
    sc_trace(mVcdFile, out_17, "(port)out_17");
    sc_trace(mVcdFile, out_17_ap_vld, "(port)out_17_ap_vld");
    sc_trace(mVcdFile, out_18, "(port)out_18");
    sc_trace(mVcdFile, out_18_ap_vld, "(port)out_18_ap_vld");
    sc_trace(mVcdFile, out_19, "(port)out_19");
    sc_trace(mVcdFile, out_19_ap_vld, "(port)out_19_ap_vld");
    sc_trace(mVcdFile, out_20, "(port)out_20");
    sc_trace(mVcdFile, out_20_ap_vld, "(port)out_20_ap_vld");
    sc_trace(mVcdFile, out_21, "(port)out_21");
    sc_trace(mVcdFile, out_21_ap_vld, "(port)out_21_ap_vld");
    sc_trace(mVcdFile, out_22, "(port)out_22");
    sc_trace(mVcdFile, out_22_ap_vld, "(port)out_22_ap_vld");
    sc_trace(mVcdFile, out_23, "(port)out_23");
    sc_trace(mVcdFile, out_23_ap_vld, "(port)out_23_ap_vld");
    sc_trace(mVcdFile, out_24, "(port)out_24");
    sc_trace(mVcdFile, out_24_ap_vld, "(port)out_24_ap_vld");
    sc_trace(mVcdFile, out_25, "(port)out_25");
    sc_trace(mVcdFile, out_25_ap_vld, "(port)out_25_ap_vld");
    sc_trace(mVcdFile, out_26, "(port)out_26");
    sc_trace(mVcdFile, out_26_ap_vld, "(port)out_26_ap_vld");
    sc_trace(mVcdFile, out_27, "(port)out_27");
    sc_trace(mVcdFile, out_27_ap_vld, "(port)out_27_ap_vld");
    sc_trace(mVcdFile, out_28, "(port)out_28");
    sc_trace(mVcdFile, out_28_ap_vld, "(port)out_28_ap_vld");
    sc_trace(mVcdFile, out_29, "(port)out_29");
    sc_trace(mVcdFile, out_29_ap_vld, "(port)out_29_ap_vld");
    sc_trace(mVcdFile, out_30, "(port)out_30");
    sc_trace(mVcdFile, out_30_ap_vld, "(port)out_30_ap_vld");
    sc_trace(mVcdFile, out_31, "(port)out_31");
    sc_trace(mVcdFile, out_31_ap_vld, "(port)out_31_ap_vld");
    sc_trace(mVcdFile, out_32, "(port)out_32");
    sc_trace(mVcdFile, out_32_ap_vld, "(port)out_32_ap_vld");
    sc_trace(mVcdFile, out_33, "(port)out_33");
    sc_trace(mVcdFile, out_33_ap_vld, "(port)out_33_ap_vld");
    sc_trace(mVcdFile, out_34, "(port)out_34");
    sc_trace(mVcdFile, out_34_ap_vld, "(port)out_34_ap_vld");
    sc_trace(mVcdFile, out_35, "(port)out_35");
    sc_trace(mVcdFile, out_35_ap_vld, "(port)out_35_ap_vld");
    sc_trace(mVcdFile, out_36, "(port)out_36");
    sc_trace(mVcdFile, out_36_ap_vld, "(port)out_36_ap_vld");
    sc_trace(mVcdFile, out_37, "(port)out_37");
    sc_trace(mVcdFile, out_37_ap_vld, "(port)out_37_ap_vld");
    sc_trace(mVcdFile, out_38, "(port)out_38");
    sc_trace(mVcdFile, out_38_ap_vld, "(port)out_38_ap_vld");
    sc_trace(mVcdFile, out_39, "(port)out_39");
    sc_trace(mVcdFile, out_39_ap_vld, "(port)out_39_ap_vld");
    sc_trace(mVcdFile, out_40, "(port)out_40");
    sc_trace(mVcdFile, out_40_ap_vld, "(port)out_40_ap_vld");
    sc_trace(mVcdFile, out_41, "(port)out_41");
    sc_trace(mVcdFile, out_41_ap_vld, "(port)out_41_ap_vld");
    sc_trace(mVcdFile, out_42, "(port)out_42");
    sc_trace(mVcdFile, out_42_ap_vld, "(port)out_42_ap_vld");
    sc_trace(mVcdFile, out_43, "(port)out_43");
    sc_trace(mVcdFile, out_43_ap_vld, "(port)out_43_ap_vld");
    sc_trace(mVcdFile, out_44, "(port)out_44");
    sc_trace(mVcdFile, out_44_ap_vld, "(port)out_44_ap_vld");
    sc_trace(mVcdFile, out_45, "(port)out_45");
    sc_trace(mVcdFile, out_45_ap_vld, "(port)out_45_ap_vld");
    sc_trace(mVcdFile, out_46, "(port)out_46");
    sc_trace(mVcdFile, out_46_ap_vld, "(port)out_46_ap_vld");
    sc_trace(mVcdFile, out_47, "(port)out_47");
    sc_trace(mVcdFile, out_47_ap_vld, "(port)out_47_ap_vld");
    sc_trace(mVcdFile, out_48, "(port)out_48");
    sc_trace(mVcdFile, out_48_ap_vld, "(port)out_48_ap_vld");
    sc_trace(mVcdFile, out_49, "(port)out_49");
    sc_trace(mVcdFile, out_49_ap_vld, "(port)out_49_ap_vld");
    sc_trace(mVcdFile, out_50, "(port)out_50");
    sc_trace(mVcdFile, out_50_ap_vld, "(port)out_50_ap_vld");
    sc_trace(mVcdFile, out_51, "(port)out_51");
    sc_trace(mVcdFile, out_51_ap_vld, "(port)out_51_ap_vld");
    sc_trace(mVcdFile, out_52, "(port)out_52");
    sc_trace(mVcdFile, out_52_ap_vld, "(port)out_52_ap_vld");
    sc_trace(mVcdFile, out_53, "(port)out_53");
    sc_trace(mVcdFile, out_53_ap_vld, "(port)out_53_ap_vld");
    sc_trace(mVcdFile, out_54, "(port)out_54");
    sc_trace(mVcdFile, out_54_ap_vld, "(port)out_54_ap_vld");
    sc_trace(mVcdFile, out_55, "(port)out_55");
    sc_trace(mVcdFile, out_55_ap_vld, "(port)out_55_ap_vld");
    sc_trace(mVcdFile, out_56, "(port)out_56");
    sc_trace(mVcdFile, out_56_ap_vld, "(port)out_56_ap_vld");
    sc_trace(mVcdFile, out_57, "(port)out_57");
    sc_trace(mVcdFile, out_57_ap_vld, "(port)out_57_ap_vld");
    sc_trace(mVcdFile, out_58, "(port)out_58");
    sc_trace(mVcdFile, out_58_ap_vld, "(port)out_58_ap_vld");
    sc_trace(mVcdFile, out_59, "(port)out_59");
    sc_trace(mVcdFile, out_59_ap_vld, "(port)out_59_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sext_ln24_fu_1202_p1, "sext_ln24_fu_1202_p1");
    sc_trace(mVcdFile, sext_ln24_reg_1438, "sext_ln24_reg_1438");
    sc_trace(mVcdFile, res_fu_1210_p2, "res_fu_1210_p2");
    sc_trace(mVcdFile, res_reg_1443, "res_reg_1443");
    sc_trace(mVcdFile, sext_ln24_1_fu_1222_p1, "sext_ln24_1_fu_1222_p1");
    sc_trace(mVcdFile, sext_ln24_1_reg_1448, "sext_ln24_1_reg_1448");
    sc_trace(mVcdFile, i_fu_1232_p2, "i_fu_1232_p2");
    sc_trace(mVcdFile, i_reg_1456, "i_reg_1456");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, mul_ln24_fu_1364_p2, "mul_ln24_fu_1364_p2");
    sc_trace(mVcdFile, mul_ln24_reg_1461, "mul_ln24_reg_1461");
    sc_trace(mVcdFile, icmp_ln17_fu_1226_p2, "icmp_ln17_fu_1226_p2");
    sc_trace(mVcdFile, i_0_reg_1190, "i_0_reg_1190");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, y_fu_1373_p2, "y_fu_1373_p2");
    sc_trace(mVcdFile, res_fu_1210_p0, "res_fu_1210_p0");
    sc_trace(mVcdFile, res_fu_1210_p1, "res_fu_1210_p1");
    sc_trace(mVcdFile, sext_ln34_fu_1206_p1, "sext_ln34_fu_1206_p1");
    sc_trace(mVcdFile, add_ln24_1_fu_1216_p2, "add_ln24_1_fu_1216_p2");
    sc_trace(mVcdFile, x_fu_1238_p62, "x_fu_1238_p62");
    sc_trace(mVcdFile, mul_ln24_fu_1364_p1, "mul_ln24_fu_1364_p1");
    sc_trace(mVcdFile, add_ln24_fu_1369_p2, "add_ln24_fu_1369_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("lec8Ex1.hdltvin.dat");
    mHdltvoutHandle.open("lec8Ex1.hdltvout.dat");
}

lec8Ex1::~lec8Ex1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete lec8Ex1_mux_606_3bkb_U1;
}

void lec8Ex1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_1190 = i_reg_1456.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_1190 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_1456 = i_fu_1232_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_1226_p2.read(), ap_const_lv1_0))) {
        mul_ln24_reg_1461 = mul_ln24_fu_1364_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        res_reg_1443 = res_fu_1210_p2.read();
        sext_ln24_1_reg_1448 = sext_ln24_1_fu_1222_p1.read();
        sext_ln24_reg_1438 = sext_ln24_fu_1202_p1.read();
    }
}

void lec8Ex1::thread_add_ln24_1_fu_1216_p2() {
    add_ln24_1_fu_1216_p2 = (!sext_ln34_fu_1206_p1.read().is_01() || !ap_const_lv17_27.is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln34_fu_1206_p1.read()) + sc_biguint<17>(ap_const_lv17_27));
}

void lec8Ex1::thread_add_ln24_fu_1369_p2() {
    add_ln24_fu_1369_p2 = (!res_reg_1443.read().is_01() || !mul_ln24_reg_1461.read().is_01())? sc_lv<32>(): (sc_biguint<32>(res_reg_1443.read()) + sc_biguint<32>(mul_ln24_reg_1461.read()));
}

void lec8Ex1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void lec8Ex1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void lec8Ex1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void lec8Ex1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_fu_1226_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void lec8Ex1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void lec8Ex1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_fu_1226_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void lec8Ex1::thread_i_fu_1232_p2() {
    i_fu_1232_p2 = (!i_0_reg_1190.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_0_reg_1190.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void lec8Ex1::thread_icmp_ln17_fu_1226_p2() {
    icmp_ln17_fu_1226_p2 = (!i_0_reg_1190.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_1190.read() == ap_const_lv6_3C);
}

void lec8Ex1::thread_mul_ln24_fu_1364_p1() {
    mul_ln24_fu_1364_p1 =  (sc_lv<16>) (sext_ln24_reg_1438.read());
}

void lec8Ex1::thread_mul_ln24_fu_1364_p2() {
    mul_ln24_fu_1364_p2 = (!x_fu_1238_p62.read().is_01() || !mul_ln24_fu_1364_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(x_fu_1238_p62.read()) * sc_bigint<16>(mul_ln24_fu_1364_p1.read());
}

void lec8Ex1::thread_out_0() {
    out_0 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_0_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(ap_const_lv6_0, i_0_reg_1190.read()))) {
        out_0_ap_vld = ap_const_logic_1;
    } else {
        out_0_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_1() {
    out_1 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_10() {
    out_10 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_10_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_A))) {
        out_10_ap_vld = ap_const_logic_1;
    } else {
        out_10_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_11() {
    out_11 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_11_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_B))) {
        out_11_ap_vld = ap_const_logic_1;
    } else {
        out_11_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_12() {
    out_12 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_12_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_C))) {
        out_12_ap_vld = ap_const_logic_1;
    } else {
        out_12_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_13() {
    out_13 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_13_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_D))) {
        out_13_ap_vld = ap_const_logic_1;
    } else {
        out_13_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_14() {
    out_14 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_14_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_E))) {
        out_14_ap_vld = ap_const_logic_1;
    } else {
        out_14_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_15() {
    out_15 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_15_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_F))) {
        out_15_ap_vld = ap_const_logic_1;
    } else {
        out_15_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_16() {
    out_16 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_16_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_10))) {
        out_16_ap_vld = ap_const_logic_1;
    } else {
        out_16_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_17() {
    out_17 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_17_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_11))) {
        out_17_ap_vld = ap_const_logic_1;
    } else {
        out_17_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_18() {
    out_18 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_18_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_12))) {
        out_18_ap_vld = ap_const_logic_1;
    } else {
        out_18_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_19() {
    out_19 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_19_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_13))) {
        out_19_ap_vld = ap_const_logic_1;
    } else {
        out_19_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_1_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1))) {
        out_1_ap_vld = ap_const_logic_1;
    } else {
        out_1_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_2() {
    out_2 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_20() {
    out_20 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_20_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_14))) {
        out_20_ap_vld = ap_const_logic_1;
    } else {
        out_20_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_21() {
    out_21 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_21_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_15))) {
        out_21_ap_vld = ap_const_logic_1;
    } else {
        out_21_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_22() {
    out_22 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_22_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_16))) {
        out_22_ap_vld = ap_const_logic_1;
    } else {
        out_22_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_23() {
    out_23 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_23_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_17))) {
        out_23_ap_vld = ap_const_logic_1;
    } else {
        out_23_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_24() {
    out_24 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_24_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_18))) {
        out_24_ap_vld = ap_const_logic_1;
    } else {
        out_24_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_25() {
    out_25 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_25_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_19))) {
        out_25_ap_vld = ap_const_logic_1;
    } else {
        out_25_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_26() {
    out_26 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_26_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1A))) {
        out_26_ap_vld = ap_const_logic_1;
    } else {
        out_26_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_27() {
    out_27 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_27_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1B))) {
        out_27_ap_vld = ap_const_logic_1;
    } else {
        out_27_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_28() {
    out_28 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_28_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1C))) {
        out_28_ap_vld = ap_const_logic_1;
    } else {
        out_28_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_29() {
    out_29 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_29_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1D))) {
        out_29_ap_vld = ap_const_logic_1;
    } else {
        out_29_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_2_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2))) {
        out_2_ap_vld = ap_const_logic_1;
    } else {
        out_2_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_3() {
    out_3 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_30() {
    out_30 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_30_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1E))) {
        out_30_ap_vld = ap_const_logic_1;
    } else {
        out_30_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_31() {
    out_31 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_31_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_1F))) {
        out_31_ap_vld = ap_const_logic_1;
    } else {
        out_31_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_32() {
    out_32 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_32_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_20))) {
        out_32_ap_vld = ap_const_logic_1;
    } else {
        out_32_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_33() {
    out_33 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_33_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_21))) {
        out_33_ap_vld = ap_const_logic_1;
    } else {
        out_33_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_34() {
    out_34 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_34_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_22))) {
        out_34_ap_vld = ap_const_logic_1;
    } else {
        out_34_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_35() {
    out_35 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_35_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_23))) {
        out_35_ap_vld = ap_const_logic_1;
    } else {
        out_35_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_36() {
    out_36 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_36_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_24))) {
        out_36_ap_vld = ap_const_logic_1;
    } else {
        out_36_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_37() {
    out_37 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_37_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_25))) {
        out_37_ap_vld = ap_const_logic_1;
    } else {
        out_37_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_38() {
    out_38 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_38_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_26))) {
        out_38_ap_vld = ap_const_logic_1;
    } else {
        out_38_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_39() {
    out_39 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_39_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_27))) {
        out_39_ap_vld = ap_const_logic_1;
    } else {
        out_39_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_3_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3))) {
        out_3_ap_vld = ap_const_logic_1;
    } else {
        out_3_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_4() {
    out_4 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_40() {
    out_40 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_40_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_28))) {
        out_40_ap_vld = ap_const_logic_1;
    } else {
        out_40_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_41() {
    out_41 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_41_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_29))) {
        out_41_ap_vld = ap_const_logic_1;
    } else {
        out_41_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_42() {
    out_42 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_42_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2A))) {
        out_42_ap_vld = ap_const_logic_1;
    } else {
        out_42_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_43() {
    out_43 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_43_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2B))) {
        out_43_ap_vld = ap_const_logic_1;
    } else {
        out_43_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_44() {
    out_44 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_44_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2C))) {
        out_44_ap_vld = ap_const_logic_1;
    } else {
        out_44_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_45() {
    out_45 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_45_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2D))) {
        out_45_ap_vld = ap_const_logic_1;
    } else {
        out_45_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_46() {
    out_46 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_46_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2E))) {
        out_46_ap_vld = ap_const_logic_1;
    } else {
        out_46_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_47() {
    out_47 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_47_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_2F))) {
        out_47_ap_vld = ap_const_logic_1;
    } else {
        out_47_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_48() {
    out_48 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_48_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_30))) {
        out_48_ap_vld = ap_const_logic_1;
    } else {
        out_48_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_49() {
    out_49 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_49_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_31))) {
        out_49_ap_vld = ap_const_logic_1;
    } else {
        out_49_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_4_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_4))) {
        out_4_ap_vld = ap_const_logic_1;
    } else {
        out_4_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_5() {
    out_5 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_50() {
    out_50 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_50_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_32))) {
        out_50_ap_vld = ap_const_logic_1;
    } else {
        out_50_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_51() {
    out_51 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_51_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_33))) {
        out_51_ap_vld = ap_const_logic_1;
    } else {
        out_51_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_52() {
    out_52 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_52_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_34))) {
        out_52_ap_vld = ap_const_logic_1;
    } else {
        out_52_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_53() {
    out_53 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_53_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_35))) {
        out_53_ap_vld = ap_const_logic_1;
    } else {
        out_53_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_54() {
    out_54 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_54_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_36))) {
        out_54_ap_vld = ap_const_logic_1;
    } else {
        out_54_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_55() {
    out_55 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_55_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_37))) {
        out_55_ap_vld = ap_const_logic_1;
    } else {
        out_55_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_56() {
    out_56 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_56_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_38))) {
        out_56_ap_vld = ap_const_logic_1;
    } else {
        out_56_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_57() {
    out_57 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_57_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_39))) {
        out_57_ap_vld = ap_const_logic_1;
    } else {
        out_57_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_58() {
    out_58 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_58_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3A))) {
        out_58_ap_vld = ap_const_logic_1;
    } else {
        out_58_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_59() {
    out_59 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_59_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         ((((esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3F) || 
             esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3E)) || 
            esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3D)) || 
           esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3C)) || 
          esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_3B)))) {
        out_59_ap_vld = ap_const_logic_1;
    } else {
        out_59_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_5_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_5))) {
        out_5_ap_vld = ap_const_logic_1;
    } else {
        out_5_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_6() {
    out_6 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_6_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_6))) {
        out_6_ap_vld = ap_const_logic_1;
    } else {
        out_6_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_7() {
    out_7 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_7_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_7))) {
        out_7_ap_vld = ap_const_logic_1;
    } else {
        out_7_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_8() {
    out_8 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_8_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_8))) {
        out_8_ap_vld = ap_const_logic_1;
    } else {
        out_8_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_out_9() {
    out_9 = y_fu_1373_p2.read();
}

void lec8Ex1::thread_out_9_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,6,6>(i_0_reg_1190.read(), ap_const_lv6_9))) {
        out_9_ap_vld = ap_const_logic_1;
    } else {
        out_9_ap_vld = ap_const_logic_0;
    }
}

void lec8Ex1::thread_res_fu_1210_p0() {
    res_fu_1210_p0 = c.read();
}

void lec8Ex1::thread_res_fu_1210_p1() {
    res_fu_1210_p1 = c.read();
}

void lec8Ex1::thread_res_fu_1210_p2() {
    res_fu_1210_p2 = (!res_fu_1210_p0.read().is_01() || !res_fu_1210_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(res_fu_1210_p0.read()) * sc_bigint<32>(res_fu_1210_p1.read());
}

void lec8Ex1::thread_sext_ln24_1_fu_1222_p1() {
    sext_ln24_1_fu_1222_p1 = esl_sext<32,17>(add_ln24_1_fu_1216_p2.read());
}

void lec8Ex1::thread_sext_ln24_fu_1202_p1() {
    sext_ln24_fu_1202_p1 = esl_sext<32,16>(a.read());
}

void lec8Ex1::thread_sext_ln34_fu_1206_p1() {
    sext_ln34_fu_1206_p1 = esl_sext<17,16>(b.read());
}

void lec8Ex1::thread_y_fu_1373_p2() {
    y_fu_1373_p2 = (!sext_ln24_1_reg_1448.read().is_01() || !add_ln24_fu_1369_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(sext_ln24_1_reg_1448.read()) + sc_biguint<32>(add_ln24_fu_1369_p2.read()));
}

void lec8Ex1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_1226_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void lec8Ex1::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0\" :  \"" << in_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1\" :  \"" << in_1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2\" :  \"" << in_2.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3\" :  \"" << in_3.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_4\" :  \"" << in_4.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_5\" :  \"" << in_5.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_6\" :  \"" << in_6.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_7\" :  \"" << in_7.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_8\" :  \"" << in_8.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_9\" :  \"" << in_9.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_10\" :  \"" << in_10.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_11\" :  \"" << in_11.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_12\" :  \"" << in_12.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_13\" :  \"" << in_13.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_14\" :  \"" << in_14.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_15\" :  \"" << in_15.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_16\" :  \"" << in_16.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_17\" :  \"" << in_17.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_18\" :  \"" << in_18.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_19\" :  \"" << in_19.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_20\" :  \"" << in_20.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_21\" :  \"" << in_21.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_22\" :  \"" << in_22.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_23\" :  \"" << in_23.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_24\" :  \"" << in_24.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_25\" :  \"" << in_25.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_26\" :  \"" << in_26.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_27\" :  \"" << in_27.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_28\" :  \"" << in_28.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_29\" :  \"" << in_29.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_30\" :  \"" << in_30.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_31\" :  \"" << in_31.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_32\" :  \"" << in_32.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_33\" :  \"" << in_33.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_34\" :  \"" << in_34.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_35\" :  \"" << in_35.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_36\" :  \"" << in_36.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_37\" :  \"" << in_37.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_38\" :  \"" << in_38.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_39\" :  \"" << in_39.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_40\" :  \"" << in_40.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_41\" :  \"" << in_41.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_42\" :  \"" << in_42.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_43\" :  \"" << in_43.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_44\" :  \"" << in_44.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_45\" :  \"" << in_45.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_46\" :  \"" << in_46.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_47\" :  \"" << in_47.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_48\" :  \"" << in_48.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_49\" :  \"" << in_49.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_50\" :  \"" << in_50.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_51\" :  \"" << in_51.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_52\" :  \"" << in_52.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_53\" :  \"" << in_53.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_54\" :  \"" << in_54.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_55\" :  \"" << in_55.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_56\" :  \"" << in_56.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_57\" :  \"" << in_57.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_58\" :  \"" << in_58.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_59\" :  \"" << in_59.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a\" :  \"" << a.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"c\" :  \"" << c.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0\" :  \"" << out_0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_ap_vld\" :  \"" << out_0_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1\" :  \"" << out_1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_ap_vld\" :  \"" << out_1_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2\" :  \"" << out_2.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2_ap_vld\" :  \"" << out_2_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3\" :  \"" << out_3.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3_ap_vld\" :  \"" << out_3_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4\" :  \"" << out_4.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4_ap_vld\" :  \"" << out_4_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5\" :  \"" << out_5.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5_ap_vld\" :  \"" << out_5_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6\" :  \"" << out_6.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6_ap_vld\" :  \"" << out_6_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7\" :  \"" << out_7.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7_ap_vld\" :  \"" << out_7_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_8\" :  \"" << out_8.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_8_ap_vld\" :  \"" << out_8_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_9\" :  \"" << out_9.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_9_ap_vld\" :  \"" << out_9_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_10\" :  \"" << out_10.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_10_ap_vld\" :  \"" << out_10_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_11\" :  \"" << out_11.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_11_ap_vld\" :  \"" << out_11_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_12\" :  \"" << out_12.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_12_ap_vld\" :  \"" << out_12_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_13\" :  \"" << out_13.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_13_ap_vld\" :  \"" << out_13_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_14\" :  \"" << out_14.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_14_ap_vld\" :  \"" << out_14_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_15\" :  \"" << out_15.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_15_ap_vld\" :  \"" << out_15_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_16\" :  \"" << out_16.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_16_ap_vld\" :  \"" << out_16_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_17\" :  \"" << out_17.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_17_ap_vld\" :  \"" << out_17_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_18\" :  \"" << out_18.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_18_ap_vld\" :  \"" << out_18_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_19\" :  \"" << out_19.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_19_ap_vld\" :  \"" << out_19_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_20\" :  \"" << out_20.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_20_ap_vld\" :  \"" << out_20_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_21\" :  \"" << out_21.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_21_ap_vld\" :  \"" << out_21_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_22\" :  \"" << out_22.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_22_ap_vld\" :  \"" << out_22_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_23\" :  \"" << out_23.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_23_ap_vld\" :  \"" << out_23_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_24\" :  \"" << out_24.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_24_ap_vld\" :  \"" << out_24_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_25\" :  \"" << out_25.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_25_ap_vld\" :  \"" << out_25_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_26\" :  \"" << out_26.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_26_ap_vld\" :  \"" << out_26_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_27\" :  \"" << out_27.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_27_ap_vld\" :  \"" << out_27_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_28\" :  \"" << out_28.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_28_ap_vld\" :  \"" << out_28_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_29\" :  \"" << out_29.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_29_ap_vld\" :  \"" << out_29_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_30\" :  \"" << out_30.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_30_ap_vld\" :  \"" << out_30_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_31\" :  \"" << out_31.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_31_ap_vld\" :  \"" << out_31_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_32\" :  \"" << out_32.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_32_ap_vld\" :  \"" << out_32_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_33\" :  \"" << out_33.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_33_ap_vld\" :  \"" << out_33_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_34\" :  \"" << out_34.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_34_ap_vld\" :  \"" << out_34_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_35\" :  \"" << out_35.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_35_ap_vld\" :  \"" << out_35_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_36\" :  \"" << out_36.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_36_ap_vld\" :  \"" << out_36_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_37\" :  \"" << out_37.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_37_ap_vld\" :  \"" << out_37_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_38\" :  \"" << out_38.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_38_ap_vld\" :  \"" << out_38_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_39\" :  \"" << out_39.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_39_ap_vld\" :  \"" << out_39_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_40\" :  \"" << out_40.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_40_ap_vld\" :  \"" << out_40_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_41\" :  \"" << out_41.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_41_ap_vld\" :  \"" << out_41_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_42\" :  \"" << out_42.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_42_ap_vld\" :  \"" << out_42_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_43\" :  \"" << out_43.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_43_ap_vld\" :  \"" << out_43_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_44\" :  \"" << out_44.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_44_ap_vld\" :  \"" << out_44_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_45\" :  \"" << out_45.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_45_ap_vld\" :  \"" << out_45_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_46\" :  \"" << out_46.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_46_ap_vld\" :  \"" << out_46_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_47\" :  \"" << out_47.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_47_ap_vld\" :  \"" << out_47_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_48\" :  \"" << out_48.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_48_ap_vld\" :  \"" << out_48_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_49\" :  \"" << out_49.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_49_ap_vld\" :  \"" << out_49_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_50\" :  \"" << out_50.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_50_ap_vld\" :  \"" << out_50_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_51\" :  \"" << out_51.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_51_ap_vld\" :  \"" << out_51_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_52\" :  \"" << out_52.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_52_ap_vld\" :  \"" << out_52_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_53\" :  \"" << out_53.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_53_ap_vld\" :  \"" << out_53_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_54\" :  \"" << out_54.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_54_ap_vld\" :  \"" << out_54_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_55\" :  \"" << out_55.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_55_ap_vld\" :  \"" << out_55_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_56\" :  \"" << out_56.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_56_ap_vld\" :  \"" << out_56_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_57\" :  \"" << out_57.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_57_ap_vld\" :  \"" << out_57_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_58\" :  \"" << out_58.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_58_ap_vld\" :  \"" << out_58_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_59\" :  \"" << out_59.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_59_ap_vld\" :  \"" << out_59_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

