-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hw4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_A_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    in_A_ce0 : OUT STD_LOGIC;
    in_A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_B_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    in_B_0_ce0 : OUT STD_LOGIC;
    in_B_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_B_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    in_B_1_ce0 : OUT STD_LOGIC;
    in_B_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_ap_vld : OUT STD_LOGIC );
end;


architecture behav of hw4 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hw4,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.644000,HLS_SYN_LAT=13,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=42,HLS_SYN_LUT=172,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal j_fu_156_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_reg_210 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln13_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_220 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_fu_201_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sum_0_reg_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_121 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln15_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln15_1_fu_187_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln15_fu_193_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln15_fu_132_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_fu_173_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln15_1_fu_179_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln15_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    j_0_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                j_0_reg_121 <= j_reg_210;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_0_reg_121 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    sum_0_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                sum_0_reg_108 <= sum_fu_201_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sum_0_reg_108 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_fu_150_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln15_reg_220 <= icmp_ln15_fu_167_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                j_reg_210 <= j_fu_156_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln13_fu_150_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln13_fu_150_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln15_fu_173_p2 <= std_logic_vector(unsigned(j_0_reg_121) + unsigned(ap_const_lv3_5));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln13_fu_150_p2)
    begin
        if (((icmp_ln13_fu_150_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln13_fu_150_p2)
    begin
        if (((icmp_ln13_fu_150_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln13_fu_150_p2 <= "1" when (j_0_reg_121 = ap_const_lv3_6) else "0";
    icmp_ln15_fu_167_p2 <= "1" when (unsigned(j_0_reg_121) < unsigned(ap_const_lv3_3)) else "0";
    in_A_address0 <= zext_ln15_fu_162_p1(3 - 1 downto 0);

    in_A_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_A_ce0 <= ap_const_logic_1;
        else 
            in_A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_B_0_address0 <= zext_ln15_1_fu_187_p1(2 - 1 downto 0);

    in_B_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_B_0_ce0 <= ap_const_logic_1;
        else 
            in_B_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_B_1_address0 <= zext_ln15_1_fu_187_p1(2 - 1 downto 0);

    in_B_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_B_1_ce0 <= ap_const_logic_1;
        else 
            in_B_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_156_p2 <= std_logic_vector(unsigned(j_0_reg_121) + unsigned(ap_const_lv3_1));
    mul_ln15_fu_132_p1 <= in_A_q0;
    mul_ln15_fu_132_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(select_ln15_fu_193_p3) * signed(mul_ln15_fu_132_p1))), 32));
    out_r <= sum_0_reg_108;

    out_r_ap_vld_assign_proc : process(ap_CS_fsm_state2, icmp_ln13_fu_150_p2)
    begin
        if (((icmp_ln13_fu_150_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_r_ap_vld <= ap_const_logic_1;
        else 
            out_r_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln15_1_fu_179_p3 <= 
        j_0_reg_121 when (icmp_ln15_fu_167_p2(0) = '1') else 
        add_ln15_fu_173_p2;
    select_ln15_fu_193_p3 <= 
        in_B_0_q0 when (icmp_ln15_reg_220(0) = '1') else 
        in_B_1_q0;
    sum_fu_201_p2 <= std_logic_vector(unsigned(sum_0_reg_108) + unsigned(mul_ln15_fu_132_p2));
    zext_ln15_1_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln15_1_fu_179_p3),64));
    zext_ln15_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_121),64));
end behav;
